### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by Mcilie** [joshdabosh/autopack#1]
I glued my computer to lego wheels and taped on a backpack. 
Now everyday i getting a fullfilling sense of happines
thank you
thank you for your contributions to humanity
the world cant move on without your inventions

**Comment by Mcilie** [comment]
When I showed my mother my replica of your creation, she cried
true tears of joy. It was as if her thousands of dollars spent
towards my education finally bore fruit. 
She was proud of what i accomplished, thanks to this nice, well documented tutorial repo.
I hope you have other Strokes of Genuis liek this

**Comment by Mcilie** [comment]
NOBEL PRIZE
NOBEL PRIZE
NOBEL PRIZE FOR JOSHI

**Comment by joshdabosh** [comment]
see
your team like
git cloned
made random inputs with preset standards
timed it
graphed results

i dunno sounds kinda sad

**Comment by Mcilie** [comment]
The louvre in paris
has officially requested to see your original model
becuase they considered the Post modern/ modern art of gluing
very artistic and unique.
Wow, you impressed both humanities and stem people
